### PR TITLE
Use fetch, remove port config

### LINKED ISSUE #30: screen doesn't
When I try to integrate Pi Hole the screen doesn't start and the following message appears in the log.

`0|MagicMirror  | [26.02.2024 08:56.24.927] [ERROR] (node:3093) UnhandledPromiseRejectionWarning: Error: Cannot find module 'node-fetch'
0|MagicMirror  | Require stack:
0|MagicMirror  | - /home/admin/MagicMirror/modules/MMM-pihole-stats/node_helper.js
0|MagicMirror  | - /home/admin/MagicMirror/js/app.js
0|MagicMirror  | - /home/admin/MagicMirror/js/electron.js
0|MagicMirror  | - /home/admin/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|MagicMirror  | -
0|MagicMirror  |     at node:internal/modules/cjs/loader:1084:15
0|MagicMirror  |     at Function.<anonymous> (node:electron/js2c/browser_init:2:116118)
0|MagicMirror  |     at Module._resolveFilename (/home/admin/MagicMirror/node_modules/module-alias/index.js:49:29)
0|MagicMirror  |     at node:internal/modules/cjs/loader:929:27
0|MagicMirror  |     at Function._load (node:electron/js2c/node_init:2:13357)
0|MagicMirror  |     at Module.require (node:internal/modules/cjs/loader:1150:19)
0|MagicMirror  |     at require (node:internal/modules/cjs/helpers:121:18)
0|MagicMirror  |     at Object.<anonymous> (/home/admin/MagicMirror/modules/MMM-pihole-stats/node_helper.js:2:15)
0|MagicMirror  |     at Module._compile (node:internal/modules/cjs/loader:1271:14)
0|MagicMirror  |     at Object..js (node:internal/modules/cjs/loader:1326:10)
0|MagicMirror  |     at Module.load (node:internal/modules/cjs/loader:1126:32)
0|MagicMirror  |     at node:internal/modules/cjs/loader:967:12
0|MagicMirror  |     at Function._load (node:electron/js2c/node_init:2:13357)
0|MagicMirror  |     at Module.require (node:internal/modules/cjs/loader:1150:19)
0|MagicMirror  |     at require (node:internal/modules/cjs/helpers:121:18)
0|MagicMirror  |     at loadModule (/home/admin/MagicMirror/js/app.js:181:19)
0|MagicMirror  | (Use `electron --trace-warnings ...` to show where the warning was created)
0|MagicMirror  | [26.02.2024 08:56.24.928] [ERROR] (node:3093) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
`

### PR DESCRIPTION
**Pull request by sheyabernstein**
This MR switches to use `fetch` because`node-fetch` was removed from MagicMirror base.

It also removes the `port` config variable.

Fixes #30

### CODE REVIEW

File: node_helper.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 const Log = require("logger");
-const fetch = require("node-fetch");
```
Comment (KristjanESPERANTO) [inline node_helper.js:2]: You didn't replaced `node-fetch` by `fetch`. You replaced `node-fetch` by deprecated `request`...

**Comment by KristjanESPERANTO** [comment]
Positive side effect: By adding package.json your module now looks nice in [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) :rocket:

File: node_helper.js (hunk 1 above)
Comment (sheyabernstein) [reply node_helper.js:2]: fetch cannot be used with require.

Feel free to open an MR with an alternative approach.

Comment (KristjanESPERANTO) [reply node_helper.js:2]: Sure. Look at #32 :slightly_smiling_face:
